#deployment/k8s-deployment.yaml : squelette pour déploiement Kubernetes

"""
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qstar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qstar
  template:
    metadata:
      labels:
        app: qstar
    spec:
      containers:
      - name: qstar-container
        image: guillaume-piron/qstar:latest
        ports:
        - containerPort: 8080
"""